  
name: AzureSpringCloud
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 11069f99-fa10-4521-941f-7e87c05ab3fc 

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }}
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build    

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_UBB_SECRETS}}

    - name: deploy to production with artifact
      uses: azure/spring-cloud-deploy@v1
      with:
        azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
        action: Deploy
        service-name: spring-2-ml-service
        app-name: cserepesvirag
        use-staging-deployment: false
        package: ${{ env.ASC_PACKAGE_PATH }}/application/**/application-0.0.1-SNAPSHOT.jar
